### ISSUE TITLE
deploy function app in ASE

### ISSUE THREAD

**Issue by mmzh** [microsoft/azure-maven-plugins#1181] opened 2020-10-22 03:03 UTC
Hi Guys, does current pom.xml support functions in App Service Environment? when I deploy java into serverless plan it's working, but when I try ASE it fails. it says "properties has invalid value". 

if current version support function in ASE, where is the documentation?  if not, can we add this?

**Comment by andxu** [comment] 2020-10-30 10:15
Sorry @mmzh , we don't support ASE and yet there is no plan to support it in the near future.

**Comment by wangmingliang-ms** [comment] 2022-09-02 07:08
Duplicate of #1097

**Closed by wangmingliang-ms** 2022-09-02 07:08 UTC
Labels: functions, feature-request, backlog
