### ISSUE TITLE
azure-webapp:deploy does not deploy war on Linux

### ISSUE THREAD

**Issue by JasonFreeberg** [Microsoft/azure-maven-plugins#352] opened 2018-08-17 23:07 UTC
### Plugin name and version

azure-webapp:deploy
version 1.3.0

### Plugin configuration in your `pom.xml`

```xml
<plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-webapp-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <resourceGroup>${azure.resourceGroup.name}</resourceGroup>
                    <appName>${azure.app.name}</appName>
                    <region>westus</region>
                    <pricingTier>S3</pricingTier>
                    <linuxRuntime>tomcat 8.5-jre8</linuxRuntime>
                    <deploymentType>war</deploymentType>

                    <resources>
                        <resource>
                            <!-- Where your artifacts are stored -->
                            <directory>${project.basedir}/target</directory>
                            <!-- Relative path to /site/wwwroot/ -->
                            <targetPath>.</targetPath>
                            <includes>
                                <include>*.war</include>
                            </includes>
                        </resource>
                    </resources>

                    <appSettings>
                        <property>
                            <name>DOCUMENTDB_URI</name>
                            <value>${DOCUMENTDB_URI}</value>
                        </property>
                        <property>
                            <name>DOCUMENTDB_KEY</name>
                            <value>${DOCUMENTDB_KEY}</value>
                        </property>
                        <property>
                            <name>DOCUMENTDB_DBNAME</name>
                            <value>${DOCUMENTDB_DBNAME}</value>
                        </property>
                    </appSettings>

                </configuration>
            </plugin>
```

### Expected behavior

The plugin should deploy and unpack the war under the wwwroot/webapps/ROOT

### Actual behavior

Deployment fails due to the default Azure 404 webpage. Error message is below (cropped for readability). It retries two more times, runs into the same problem, and ultimately fails.

```bash
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< com.microsoft.azure:todo-app-java-on-azure >-------------
[INFO] Building todo-app-java-on-azure 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.3.0:deploy (default-cli) @ todo-app-java-on-azure ---
[INFO] Authenticate with Azure CLI 2.0
[INFO] Updating target Web App...
[INFO] Successfully updated Web App.
[INFO] Deploying to Web App 'freebergTomcatDemo'...
[INFO] Deploying the war file...
[WARNING] Exception occurred when deploying war file to server: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('?' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: ?<!DOCTYPE html>
<html>
<head>
    <title>Microsoft Azure Web App - Error 404</title>
    <style type="text/css">
        html {
            height: 100%;
            width: 100%;
        }

[ cropped for readability ]

    <div id="feature">
        <div id="content">
            <h1>404 Web Site not found.</h1>
            <p>You may be seeing this error due to one of the reasons listed below :</p>
            <ul>
                <li>Custom domain has not been configured inside Azure. See <a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-tutorial-custom-domain">how to map an existing domain</a> to resolve this.</li>
                <li>Client cache is still pointing the domain to old IP address. Clear the cache by running the command <i>ipconfig/flushdns.</i></li>
            </ul>
            <p>Checkout <a href="https://blogs.msdn.microsoft.com/appserviceteam/2017/08/08/faq-app-service-domain-preview-and-custom-domains/">App Service Domain FAQ</a> for more questions.</p>
        </div>
     </div>
</body>
</html>
; line: 1, column: 2], retrying immediately (1/3)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.833 s
[INFO] Finished at: 2018-08-17T15:58:47-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.3.0:deploy (default-cli) on project todo-app-java-on-azure: Failed to deploy war file after 3 retries... -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Steps to reproduce the problem

I deployed the app successfully using curl. So I believe the problem is confined to the plugin.

### More details

Using Powershell on Windows 10

**Comment by JasonFreeberg** [comment] 2018-08-18 03:54
@jdneo Will do! Thanks for the quick response.

**Comment by JasonFreeberg** [comment] 2018-08-18 17:32
Here's the trace

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< com.microsoft.azure:todo-app-java-on-azure >-------------
[INFO] Building todo-app-java-on-azure 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.3.0:deploy (default-cli) @ todo-app-java-on-azure ---
[INFO] Authenticate with Azure CLI 2.0
[INFO] Updating target Web App...
[INFO] Successfully updated Web App.
[INFO] Deploying to Web App 'freebergTomcatDemo'...
[INFO] Deploying the war file...
[WARNING] Exception occurred when deploying war file to server: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;api&#47;wardeploy</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.29</h3></body></html>; line: 1, column: 2], retrying immediately (1/3)
[WARNING] Exception occurred when deploying war file to server: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;api&#47;wardeploy</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.29</h3></body></html>; line: 1, column: 2], retrying immediately (2/3)
[WARNING] Exception occurred when deploying war file to server: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;api&#47;wardeploy</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.29</h3></body></html>; line: 1, column: 2], retrying immediately (3/3)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:41 min
[INFO] Finished at: 2018-08-18T10:27:32-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.3.0:deploy (default-cli) on project todo-app-java-on-azure: Failed to deploy war file after 3 retries... -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.3.0:deploy (default-cli) on project todo-app-java-on-azure: Failed to deploy war file after 3 retries...
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy war file after 3 retries...
    at com.microsoft.azure.maven.AbstractAzureMojo.handleException (AbstractAzureMojo.java:347)
    at com.microsoft.azure.maven.AbstractAzureMojo.execute (AbstractAzureMojo.java:293)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy war file after 3 retries...
    at com.microsoft.azure.maven.webapp.handlers.WarArtifactHandlerImpl.publish (WarArtifactHandlerImpl.java:53)
    at com.microsoft.azure.maven.webapp.DeployMojo.deployArtifacts (DeployMojo.java:95)
    at com.microsoft.azure.maven.webapp.DeployMojo.doExecute (DeployMojo.java:49)
    at com.microsoft.azure.maven.AbstractAzureMojo.execute (AbstractAzureMojo.java:288)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by jdneo** [comment] 2018-08-20 02:25
Hi @JasonFreeberg,

Thank you for your feedback. We found that this is due to a bug in the azure java SDK. We have added an issue which can be tracked here: https://github.com/Azure/azure-libraries-for-java/issues/546

For now, the workaround is to make sure the `appName` do not have upper cases.

**Comment by JasonFreeberg** [comment] 2018-08-20 04:39
@jdneo Thanks for submitting that other ticket, and for the work-around.

**Comment by ColumWalsh** [comment] 2018-10-13 20:49
This bug still happens for the app name maven-linux-app-2018-10-13T17:44:56Z . Crazy name I know, but I hit it when following the azure tutorial https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-containerized-spring-boot-java-app-with-maven-plugin?view=azure-java-stable

**Comment by ColumWalsh** [comment] 2018-10-15 08:36
Ah, it's quite old. 0.1.3. What should I use?

**Comment by jdneo** [comment] 2018-10-15 09:10
@ColumWalsh The newest one is `1.4.1`

**Comment by ColumWalsh** [comment] 2018-10-15 13:29
I get a different exception with 1.4.1 and the app name maven-linux-app-2018-10-15t13:23:30z. 
`[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:deploy (default-cli) on project gs-spring-boot-docker: Illegal URL: https://maven-linux-app-2018-10-15t13:23:30z.scm.azurewebsites.net/ -> [Help 1]`

my plugin definition is
```
<plugin>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-webapp-maven-plugin</artifactId>
   <version>1.4.1</version>
   <configuration>
      <authentication>
         <serverId>azure-auth</serverId>
      </authentication>
      <resourceGroup>maven-plugin</resourceGroup>
      <appName>maven-linux-app-${maven.build.timestamp}</appName>
      <region>westus</region>
      <containerSettings>
         <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
      </containerSettings>
      <appSettings>
         <property>
            <name>PORT</name>
            <value>8080</value>
         </property>
      </appSettings>
   </configuration>
</plugin>
```

**Comment by SummerSun** [comment] 2018-10-17 04:36
The error message tells clearly that `Illegal URL: https://maven-linux-app-2018-10-15t13:23:30z.scm.azurewebsites.net/`.

The appname defined here `<appName>maven-linux-app-${maven.build.timestamp}</appName>` is illegal. You need to specify the timestamp format like `<maven.build.timestamp.format>yyyyMMddHHmmssSSS</maven.build.timestamp.format>`. Or use a valid app name in the configuration. You could refer the portal for the correct format of the web app name. And since the issue is not related to the original one, we will close it for better tracking. Feel free to open a new issue if you meet any other errors/exceptions.

**Closed by SummerSun** 2018-10-17 04:36 UTC
Labels: bug, external-dependency, webapps
