### ISSUE TITLE
[Functions] Add all the supported commands to CI

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#429] opened 2018-10-19 19:46 UTC
CI added https://github.com/Microsoft/azure-maven-plugins/pull/425 
is testing the archetype

```
mvn archetype:generate -DarchetypeCatalog="local" -DarchetypeGroupId="com.microsoft.azure" -DarchetypeArtifactId="azure-functions-archetype" -DarchetypeVersion="$atchetypeVersion" -DgroupId="com.microsoft" -DartifactId="e2etestproject" -Dversion="1.0-SNAPSHOT" -Dpackage="com.microsoft" -DappRegion="westus" -DresourceGroup="e2etest-java-functions-group" -DappName="e2etest-java-functions" -B
```
This needs to be moved to archetype repo CI.
CI for the plugin should do something similar, 
```
<azure.functions.maven.plugin.version>**version built by the CI**</azure.functions.maven.plugin.version>
```
Tests should include all the supported commands. Please open separate issues if this is a larger workitem

**Comment by pragnagopa** [comment] 2018-10-19 19:46
cc: @jdneo , @Flanker32

**Comment by Flanker32** [comment] 2018-10-21 14:31
@pragnagopa @jdneo  How about update the version of function maven plugin in archetype and the CI test will covers the latest archetype as well as maven plugin, it will generate function project by archetype and package it through function plugin, so i think one CI test in plugin repo is enough.

**Comment by pragnagopa** [comment] 2018-10-22 20:18
After archetype generated function project, basic verification if the the project generated builds or not should be done in the archetype repo

**Comment by kulkarnisonia16** [comment] 2019-08-15 04:07
@Flanker32 - Is this duplicate of https://github.com/microsoft/azure-maven-plugins/issues/261?

**Closed** 2022-09-02 06:40 UTC
Labels: functions, javafunctions-v2-GA-shouldhave, internal
