### ISSUE TITLE
An illegal reflective access operation has occurred when config/deploy spring project

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#1044] opened 2020-03-20 10:21 UTC
### Plugin name and version
JDK: 11
azure spring cloud maven-plugin: 1.1.0
### Plugin configuration in your `pom.xml`
```
<plugin>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-cloud-maven-plugin</artifactId>
	<version>1.1.0</version>
</plugin>
```
### Actual behavior
![image](https://user-images.githubusercontent.com/41051257/77154095-f9380d80-6ad5-11ea-924f-8701724a2429.png)

**Comment by yoshioterada** [comment] 2020-06-03 13:21
I didn't use the azure-spring-cloud-maven-plugin but I used azure-webapp-maven-plugin. Howerver same error messages was showed. 


So this will happen on ***azure-webapp-maven-plugin*** plugin too.

```xml
          <plugin>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-webapp-maven-plugin</artifactId>
            <version>1.9.1</version>
          </plugin>
```

```
$ mvn azure-webapp:config
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.yoshio3:starter-sample >---------------------
[INFO] Building starter-sample 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- azure-webapp-maven-plugin:1.9.1:config (default-cli) @ starter-sample ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields (file:/Users/yoterada/.m2/repository/com/microsoft/azure/applicationinsights-core/2.5.1/applicationinsights-core-2.5.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by bpossolo** [comment] 2020-07-06 03:34
seeing this as well

**Comment by Flanker32** [comment] 2020-07-06 04:28
@yoshioterada @bpossolo Thanks for your report, this seems to be an external issue of application insights which we used for telemetries, will fix this issue once the dependency is updated.

**Comment by noce2** [comment] 2020-12-19 23:22
@Flanker32 hi, please could you give an indication of when a fix is coming? I'm seeing this issue as well with the `azure-functions-maven-plugin 1.9.0`.

**Comment by andxu** [comment] 2021-08-09 08:37
It is caused by our dependency: applicationinsights.core, now it should be fixed in newst versions when we upgrade the applicationinsights.core to `2.6.3`

**Closed** 2021-09-08 09:16 UTC
Labels: external-dependency, need-more-info, spring
